### ISSUE TITLE
Window Crash

### ISSUE THREAD

**Issue by SirFiChi** [CyanLabs/Syn3Updater#103]
Hi folks.
After the start the programm crashes with an error.
It appears direct after the start of the program.

The screenshots:
![Crash01](https://user-images.githubusercontent.com/12483570/122158989-d8dc3780-ce6d-11eb-8077-6ed437b5989f.png)
![Crash02](https://user-images.githubusercontent.com/12483570/122158991-da0d6480-ce6d-11eb-9dae-5eca5c7e0f2c.png)
![Crash03](https://user-images.githubusercontent.com/12483570/122159685-f6f66780-ce6e-11eb-9417-2adb910b424a.png)

The link to the Crashreport:
https://cyanlabs.net/syn3-updater-crash-log/?uuid=1ebce32b-9b1e-6322-8c27-0242ac120005

 - Windows Version: 10 (21H1)
 - Syn3 Updater Version: 2.9.6.0
 - Syn3 Updater Branch: Stable

After the third picture the program closes, when I try to do something in the program.

**Comment by Fma965** [comment]
Please reset your settings from the crash window and try again.

**Comment by SirFiChi** [comment]
In did it all lot of times, also with restarting of the computer, without success. 

Am 16. Juni 2021 09:24:01 MESZ schrieb Scott ***@***.***>:
>Please reset your settings from the crash window and try again.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CyanLabs/Syn3Updater/issues/103#issuecomment-862119697

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Fma965** [comment]
I think this is fixed in the latest Alpha!

**Comment by SirFiChi** [comment]
I tried it with another computer with Win10 1809, and it works fine.
Because of the missing of other reports, I close this issue. It also could be a problem with the computer.

After all: Thanks for the great work!
