### ISSUE TITLE
SYNC3 update does not work if you don't have an 8" touch screen and does not display well on the 4" screen also no dash button response.

### ISSUE THREAD

**Issue by MEHOLM** [CyanLabs/Syn3Updater#122]
**Describe the bug**
Please explain in as much detail as possible what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 10, 8, 7]
 - Syn3 Updater Version [e.g. 2.0.0.0]
 - Syn3 Updater Branch [e.g. Stable, Beta or Alpha]

**Additional context**

**Comment by Fma965** [comment]
Thanks for reporting, this isn't really a bug though, 

The requirements clearly state that your display should look like this which a 4" screen does not.
![image](https://user-images.githubusercontent.com/1707290/123074159-f762a580-d40e-11eb-989d-1bc0b2b0e730.png)
