### ISSUE TITLE
Remote Host Disconnected

### ISSUE THREAD

**Issue by russelldilbeck** [CyanLabs/Syn3Updater#124]
**Describe the bug**
Using the Syn3 Updater 2.9.7.0 to Automatic download Sync 3.4 software and update Maps.

Region:  United States
Install Mode:  reformat
Forced:  No
MY20 Protection:  Auto-Detect

Trying to download the most recent version of Sync 3.4.21098 and NA 20 Maps
I kept getting "remote host disconnected" message.
The last line in the log would always be file:   4U5T-14G421-CFD_1615428639000.TAR.GZ (failed download)

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version 2.9.7.0
 - Syn3 Updater Branch Stable

**Additional context**
Changed the Maps version from NA 20 back to NA 19 and the download worked perfectly.

**Comment by AvdonR** [comment]
It should be noted that this has been documented for a while now and it’s most likely in large part just due to Fords servers. A workaround for this issue is to manually download the files via a browser, place them into the Syn3 Updater download folder, and run the app again. The app will scan, verify, and skip the existing downloads and create the USB.

**Comment by SanD-82** [comment]
Also, try configuring only a single download instead of 8 to see if that makes a difference.

**Comment by Fma965** [comment]
If any one has a solution for this please let me know, but as far as i can see this issue is to do with Fords (Azures) blob's

This has been extensively investigated but no solution has been found, i also can not replicate this issue which makes testing difficult.

**Comment by Amoakk** [comment]
> It should be noted that this has been documented for a while now and it’s most likely in large part just due to Fords servers. A workaround for this issue is to manually download the files via a browser, place them into the Syn3 Updater download folder, and run the app again. The app will scan, verify, and skip the existing downloads and create the USB.

Where would I manually download the files via a browser?  Unfortunately, when I go through the Ford website, it does not allow me to download 3.4 files.

Thanks for the help.

**Comment by Fma965** [comment]
> > It should be noted that this has been documented for a while now and it’s most likely in large part just due to Fords servers. A workaround for this issue is to manually download the files via a browser, place them into the Syn3 Updater download folder, and run the app again. The app will scan, verify, and skip the existing downloads and create the USB.
> 
> Where would I manually download the files via a browser? Unfortunately, when I go through the Ford website, it does not allow me to download 3.4 files.
> 
> Thanks for the help.

You can download the files manually from https://cyanlabs.net/tutorials/manual-method-update-to-3-4/#:~:text=2.%20Downloading%20the%20update%20files
