### ISSUE TITLE
Locale Request

### ISSUE THREAD

**Issue by scirre** [CyanLabs/Syn3Updater#137]
**Which language do you want added? Please describe.**
Portugues Brazil

**What is the 4/5 character code for this language, e.g EN-US etc.**
PT-Br

**Are their similiar "parent" languages, e.g EN already exists and you are wanting EN-GB?**
PT

**Comment by Fma965** [comment]
Language added to POEditor - https://poeditor.com/join/project?hash=6iNpqiacmb
