### ISSUE TITLE
Locale RequestPoland

### ISSUE THREAD

**Issue by marcindejda** [CyanLabs/Syn3Updater#138]
**Which language do you want added? Please describe.**

**What is the 4/5 character code for this language, e.g EN-US etc.**

**Are their similiar "parent" languages, e.g EN already exists and you are wanting EN-GB?**

**Comment by marcindejda** [comment]
Poland

**Comment by Fma965** [comment]
This language already exists in poeditor for adding translations . https://poeditor.com/join/project?hash=6iNpqiacmb
