### ISSUE TITLE
Locale Request

### ISSUE THREAD

**Issue by RaccoonFrom70s** [CyanLabs/Syn3Updater#144]
**Which language do you want added? Please describe.**
Finnish / "Suomi"

**What is the 4/5 character code for this language, e.g EN-US etc.**
fi-FI

**Are their similiar "parent" languages, e.g EN already exists and you are wanting EN-GB?**
No

**Comment by Fma965** [comment]
Finnish added to POEditor, please note this does not mean the language will be added, this just gives the option for people using POEditor to translate it.
