### ISSUE TITLE
Constant Error Trying to Verify File

### ISSUE THREAD

**Issue by Amoakk** [CyanLabs/Syn3Updater#148]
**Describe the bug**
Please explain in as much detail as possible what the bug is.

**To Reproduce**
Attempting update from Sync 3 Version 3.0.20204 to United States version Sync 3.4.21194 with 2.20(2020) NA map.
Hit 'Start'. Goes through process, but never gets past the third to last file. 

**Expected behavior**
The file to be verified and downloads to continue

**Screenshots**
![Error 2](https://user-images.githubusercontent.com/28128333/132718646-e633fc9b-0ccd-4355-baae-2e95670c2751.png)
![ErrorValidating](https://user-images.githubusercontent.com/28128333/132718647-a50b8612-65bc-465f-bcf5-cd1aafccdf70.png)
![Error 2](https://user-images.githubusercontent.com/28128333/132718714-0c72c804-3bf6-41d4-b343-08a1240bf568.png)
![ErrorValidating](https://user-images.githubusercontent.com/28128333/132718721-fc407bcf-de27-4113-833a-ba68a1188f73.png)

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version 2.10.3.0
 - Syn3 Updater Branch: Stable

**Additional context**

**Comment by Fma965** [comment]
Nothing i can do about this, the issue is with your network connection or computer it self.
