### ISSUE TITLE
"Start" button does nothing

### ISSUE THREAD

**Issue by drguitarum2005** [CyanLabs/Syn3Updater#158]
**Describe the bug**
I've successfully used Syn3Updater in the past with no issue. Trying to do the latest update to a USB drive (same drive I've used before) and nothing happens when I click "Start". The buttons gray out as if it was going to do something but nothing is happening. If I switch tabs (e.g. go to Logs, or Settings) and switch back home, "Start" is green again and I can click it again. Again with no response.

**To Reproduce**
1. Go to 'home'
2. Select USB drive
3. Select region (US)
4. Select version (3.4.21265)
5. Select map version (keep existing)
6. Click "Start"

**Expected behavior**
Files will write to USB drive, ready to boot Sync 3 from

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: 10 Pro
 - Syn3 Updater Version: 2.10.6.0 (stable)
 - Syn3 Updater Branch : Stable

**Additional context**
No OS changes have been made

**Comment by Fma965** [comment]
I can't replicate this.
