### ISSUE TITLE
Crashing upon opening on Windows 11

### ISSUE THREAD

**Issue by XICavyIX** [CyanLabs/Syn3Updater#159]
Details:
System.NullReferenceException<br>Object reference not set to an instance of an object.<br><br><br><br>   at Cyanlabs.Syn3Updater.AppMan.LoadProfile() in D:\GitHub\Syn3Updater\Syn3Updater\AppMan.cs:line 361
   at Cyanlabs.Syn3Updater.AppMan.Initialize() in D:\GitHub\Syn3Updater\Syn3Updater\AppMan.cs:line 228
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)<br><br>0<br>8
LoadProfile
Syn3Updater, Version=2.10.6.0, Culture=neutral, PublicKeyToken=null
Cyanlabs.Syn3Updater.AppMan
Void LoadProfile()<br>-2147467261<br>Syn3Updater<br>

JSON Output:
"{\"ErrorName\":\"System.NullReferenceException\",\"ErrorLocation\":\"\/TryCatchWhen\/0\",\"Logs\":[{\"Log\":\"Syn3 Updater 2.10.6.0 (Stable) is Starting\",\"Time\":\"2021-11-14T10:10:02.9378153-07:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"URL Intent: \",\"Time\":\"2021-11-14T10:10:02.9383114-07:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"MainSettings found in LocalAppDataPath\",\"Time\":\"2021-11-14T10:10:02.9388093-07:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"MainSettings loaded successfully\",\"Time\":\"2021-11-14T10:10:03.0459434-07:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Profile default loaded\",\"Time\":\"2021-11-14T10:10:03.0474328-07:00\",\"Caller\":\"LoadProfile\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"System.NullReferenceException\",\"Time\":\"2021-11-14T10:10:03.3556623-07:00\",\"Caller\":\"CrashWindow\",\"LogType\":\"Crash\",\"Exception\":{\"ClassName\":\"System.NullReferenceException\",\"Message\":\"Object reference not set to an instance of an object.\",\"Data\":{\"System.Object\":null},\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Cyanlabs.Syn3Updater.AppMan.LoadProfile() in D:\\\\GitHub\\\\Syn3Updater\\\\Syn3Updater\\\\AppMan.cs:line 361\\r\\n   at Cyanlabs.Syn3Updater.AppMan.Initialize() in D:\\\\GitHub\\\\Syn3Updater\\\\Syn3Updater\\\\AppMan.cs:line 228\\r\\n   at System.Windows.Application.<.ctor>b__1_0(Object unused)\\r\\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\\r\\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":\"8\\nLoadProfile\\nSyn3Updater, Version=2.10.6.0, Culture=neutral, PublicKeyToken=null\\nCyanlabs.Syn3Updater.AppMan\\nVoid LoadProfile()\",\"HResult\":-2147467261,\"Source\":\"Syn3Updater\",\"WatsonBuckets\":null}}]}"

**Comment by Fma965** [comment]
Your settings file appears invalid, delete the Syn3 Updater folder at `C:\Users\USERNAME\AppData\Local\CyanLabs\Syn3 Updater`

**Comment by Fma965** [comment]
also please use the bug report template....

**Describe the bug**
Please explain in as much detail as possible what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 10, 8, 7]
 - Syn3 Updater Version [e.g. 2.0.0.0]
 - Syn3 Updater Branch [e.g. Stable, Beta or Alpha]

**Additional context**
Add any other context about the problem here.
