### ISSUE TITLE
Even with MY20 protection enabled, reformat can be chosen as install method

### ISSUE THREAD

**Issue by SanD-82** [CyanLabs/Syn3Updater#162]
**Describe the bug**
For instance, if you configure your current version as 3.0.xxxx ANZ and enable MY20 protection, Syn3updater won't give you the option to choose 3.4.xxxx with 1.20 Maps, 1.19 MAPS are shown since they are not locked.
But if you choose 1.19 MAPS, installation method is REFORMAT, which is contradictory with MY20 protection being enabled and not offering 1.20 maps.

**To Reproduce**
1. Configure current version 3.0.xxxx
2. Activate MY20 Protection (no autodetect, but enabled)
3. Chose 3.4.xxxx with maps.
4. Result: only 1.19 maps are offered and install method is set to reformat

**Expected behavior**
If MY20 protection is enabled, reformat should not be selected.
And if so, 1.20 maps should be also be offered.
Maybe a viable solution would be to set a "incompatible settings" scenario.

**Screenshots**
![image](https://user-images.githubusercontent.com/85264826/145851515-2211a51e-5666-4a8b-adc8-165455cced98.png)

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version:  2.10.6.0
 - Syn3 Updater Branch: Stable

**Comment by Fma965** [comment]
Thanks, not sure if i will be releasing a  new version of Syn3 Updater v2.x but if i do i will fix this :)
