### ISSUE TITLE
Sync updater crashed

### ISSUE THREAD

**Issue by jseiden420** [CyanLabs/Syn3Updater#163]
I keep getting the error "sync updater crashed" when I try to enter any information in the "full version" box.  I tried to reinstall and reset settings but nothing changes.

**Comment by jseiden420** [comment]
https://cyanlabs.net/syn3-updater-crash-log/?uuid=1ec5d20f-668b-6980-8fb0-0242ac12000e

**Comment by Fma965** [comment]
Whats your ISP (Internet Service Provider)?
Can you access https://syn3updater.cyanlabs.net ?

**Comment by Fma965** [comment]
Closing as no reply from bug reporter
