### ISSUE TITLE
If the current and new version are the same, a popup should not appear

### ISSUE THREAD

**Issue by SanD-82** [CyanLabs/Syn3Updater#170]
**Describe the bug**
If you need to force an installation method and the current and new version are the same, this message should not appear at the end of the process:

![image](https://user-images.githubusercontent.com/85264826/157553435-e3a3e060-9b5b-4bf9-aebd-51154acf938e.png)

**To Reproduce**
Set your current and new version as the same.

**Expected behavior**
Since versions are the same, the question should not be asked.

**Screenshots**
![image](https://user-images.githubusercontent.com/85264826/157553547-e654f04c-67f9-4831-bc46-9d1a52bc90be.png)

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version 2.10.8.0
 - Syn3 Updater Branch Stable

**Comment by Fma965** [comment]
Thanks for the bug report :)

**Comment by SanD-82** [comment]
You are welcome!
I know syn3updater 2.x is almost EOS and EOL, but something to keep in mind to the next version, if applicable.

**Comment by Fma965** [comment]
yeah most of the code will be re-written, i'm still deciding whether it's worth the effort, but i'm waiting on MAUI to be released first anyway
