### ISSUE TITLE
Download / USB creation aborts on Fast User Switching / RDP connection

### ISSUE THREAD

**Issue by TheShadowghost** [CyanLabs/Syn3Updater#178]
**Describe the bug**
When connecting via RDP or using Fast User Switching to reconnect to your session, the Application will abort the current Task throwing an error, that a required File is being in use. The download can be restarted without issues.

**To Reproduce**
1. Start the Download of a Sync 3 package
2a. Start an RDP Session
2b Use Fast User Switching in the Windows start menu by selecting a different user and immediately logging back into your account.
3. Syn3 Updater has aborted the download and throws an Error of a File being in use after clicking in the Syn3 window once.

**Expected behavior**
The Download and preparing the USB should continue normally even when the Session gets reconnected.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9335303/171502759-31259d83-4269-4cde-8a8a-107b70e70b2c.png)

**Desktop (please complete the following information):**
 - Windows Version: [Windows 10 21h2 (19044.1706)]
 - Syn3 Updater Version [2.10.11.0]
 - Syn3 Updater Branch [Stable]

**Additional context**
Message that started the conversation: https://discord.com/channels/133641094997999617/810944914309120050/981657365214547968
This is a really niche issue and probably won't affect a lot of people.

**Comment by Fma965** [comment]
Honestly this is such a niche scenario, i won't spend time fixing this, if i ever decide to rewrite Syn3 Updater for V3 then maybe.
