### ISSUE TITLE
Wrongly handles empty ECU model in XML 

### ISSUE THREAD

**Issue by Fma965** [CyanLabs/Syn3Updater#180]
If the XML contains a empty ECU Delivery Assembly Number then it assumes it's not MY20 as it doesn't match known MY20 models... this is wrong....

**Comment by zoom1981** [comment]
![изображение](https://user-images.githubusercontent.com/110667678/183061288-05d11338-8b9b-4123-8805-30e7e789a0a1.png)
Hello, I have an error on the questionnaire file in the program.
[Sync_LV89007Q_WF0JXXWPCJGE21897.zip](https://github.com/CyanLabs/Syn3Updater/files/9267917/Sync_LV89007Q_WF0JXXWPCJGE21897.zip)

would like to know how much memory?

**Comment by Fma965** [comment]
As stated in the error please contact us via our forum or discord, this is not a Syn3 Updater issue, its a Ford interrogator log issue...

https://community.cyanlabs.net/
https://discord.gg/wnSr7JB3Vk

**Comment by Fma965** [comment]
FWIW it looks to be 32GB but that interrogator log is from 2021....

**Comment by zoom1981** [comment]
strange, maybe the date was reset on the auto time or on the laptop
