### ISSUE TITLE
Syn3Updater Crash

### ISSUE THREAD

**Issue by andspenka** [CyanLabs/Syn3Updater#185]
When crating multiple USB sticks, as 1 USB is finished I go back to change the current version and Syn3Updater crashes.

**To Reproduce**
1. Enter current version & click Apply Settings
2. Create USB, although I get the same issue even if I don't create any USB and just go back to change the version.
3. Click in the Current Version box, if you click on the 'X' or delete the numbers already in the box, when you start to type the new number the program crashes.

**Expected behavior**
Enter new version and click Apply, then create new USB.

**Screenshots**
![Cyanlabs Crash](https://user-images.githubusercontent.com/112126869/186766364-70376096-022a-42d9-8a3c-9fa9fed0c5f5.jpg)

**Desktop (please complete the following information):**
 - Windows Version: Windows 11
 - Syn3 Updater Version: 2.11.4.0
 - Syn3 Updater Branch: Stable

**Additional context**

**Comment by Fma965** [comment]
Fixed, no need for a new application version
