### ISSUE TITLE
Sync3 doesn't work anymore

### ISSUE THREAD

**Issue by Franco20040** [CyanLabs/Syn3Updater#186]
**Describe the bug**
I downloaded the zip file and follower accurately all the instruction till I inserted my USB driver in the car, but after the windows "software update founded..." Appear the ford logo with a sentence that says "starting Update..." but after few seconds, appear an orange screen with the sentence " Error update package not found..." And there is no way to return back.

**To Reproduce**
1. Go to '....'

**Expected behavior**
I expect that after the ford logo, will happen the loading of the update.

**Screenshots**
2 screenshots of the bug, and one of the old version of the sync3

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version [2.11.4.0]
 - Syn3 Updater Branch [Stable]

**Additional context**
Before that, my sync3 version was 2.3, build 17109, please help me.
![20220925_151707](https://user-images.githubusercontent.com/91467763/192145867-45ff61bc-c36d-4f75-859e-576b68293451.jpg)
![20220925_151703](https://user-images.githubusercontent.com/91467763/192145869-8472727e-54a0-4a02-b107-757fc663962e.jpg)
![20220925_114306](https://user-images.githubusercontent.com/91467763/192145872-4b3e019e-b2e4-49aa-9113-283c9b689264.jpg)

**Comment by Fma965** [comment]
This is not a  Syn3Updater issue, post on our forum https://community.cyanlabs.net

**Comment by Franco20040** [comment]
Sorry, now I'm trying to redownload the files on the Usb driver, and
retrying because before there was another usb in the car during the
process...

Franco Policicchio

Il Dom 25 Set 2022, 15:38 Scott ***@***.***> ha scritto:
