### ISSUE TITLE
Syn3Updater Crashes

### ISSUE THREAD

**Issue by CaptainMorgans** [CyanLabs/Syn3Updater#188]
**Describe the bug**
Please explain in as much detail as possible what the bug is.
Open the Launcher.exe and application says loading, then crashes. 
**To Reproduce**
2. Click on 'Launcher.exe'
Faulting application name: Launcher.exe_Launcher, version: 2.11.8.0, time stamp: 0x8e157f04
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2193, time stamp: 0x7f7062e1
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process ID: 0x19f0
Faulting application start time: 0x01d90e78dd0fdd77
Faulting application path: C:\Program Files (x86)\CyanLabs\Syn3Updater\Launcher.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 0b8768c3-ddad-4320-8135-41cb12fcef1d
Faulting package full name: 
Faulting package-relative application ID: 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: 10 Pro
 - Syn3 Updater Version: Latest as at December 2022
 - Syn3 Updater Branch: Stable

**Additional context**
I have uninstalled dot net 4.8 and reinstalled it with reboots after those steps. Application still crashes.

[Syn3Updater Errors.txt](https://github.com/CyanLabs/Syn3Updater/files/10212589/Syn3Updater.Errors.txt)

**Comment by Fma965** [comment]
Exception Info: System.Net.WebException

For whatever reason you are unable to access the GitHub API, whether this is a firewall issue or a internet connection issue I do not know.

The launcher needs to download the latest files from GitHub but is not able to do so

However this is not a issue with syn3updater so  I am closing the issue.
