### ISSUE TITLE
App crashes on launch if no Internet connection

### ISSUE THREAD

**Issue by rcmaehl** [CyanLabs/Syn3Updater#189]
The app does not seem to be able to launch if there is no Internet connection, or the Internet connection is too slow such as a mobile hotspot.

**Comment by Fma965** [comment]
Not a bug, the app requires internet connectivity to pull data from cyanlabs for lists of packages and releases etc.

**Comment by Fma965** [comment]
You need internet to use this app, so no reason to spend time resolving this.
