### ISSUE TITLE
Add ability to continue from interruption

### ISSUE THREAD

**Issue by rcmaehl** [CyanLabs/Syn3Updater#190]
Add an ability for the app to continue from where it left off if there was an interruption. Verify the already downloaded files, download any that are required, and start or resume the file copy. It seems silly to completely restart the process, let alone very annoying for those using USB 2.0 media

**Comment by Fma965** [comment]
This won't be added, too much effort for little reward, anyone using a usb 2.0 drive needs to update, it's 2023.

**Comment by rcmaehl** [comment]
> This won't be added, too much effort for little reward, anyone using a usb 2.0 drive needs to update, it's 2023.

Valid.
