### ISSUE TITLE
compass not working after update 3.4

### ISSUE THREAD

**Issue by AnilSinghAttri** [CyanLabs/Syn3Updater#192]
**Describe the bug**
Please explain in as much detail as possible what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 10, 8, 7]
 - Syn3 Updater Version [e.g. 2.0.0.0]
 - Syn3 Updater Branch [e.g. Stable, Beta or Alpha]

**Additional context**

**Comment by AnilSinghAttri** [comment]
Compass not working after updated 3.4

**Comment by Fma965** [comment]
Not a issue with the syn3updater application, post on our forum instead.
