### ISSUE TITLE
usb error

### ISSUE THREAD

**Issue by stevevai38** [CyanLabs/Syn3Updater#194]
**Describe the bug**
I can't use syn3 updater. no usb key is detected by the software.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: 11
 - Syn3 Updater Version 2.11.9.0
 - Syn3 Updater Branch Stable
![P_20230522_081157](https://github.com/CyanLabs/Syn3Updater/assets/134260940/90bda92f-cf0e-4c3c-83a6-0bf7ed11ad79)

**Comment by Fma965** [comment]
No information provided, error message not in english, no idea what the error says.

**Comment by Fma965** [comment]
No information provided, closed
