### ISSUE TITLE
Locale Request

### ISSUE THREAD

**Issue by bachi1968** [CyanLabs/Syn3Updater#197]
**Which language do you want added? Please describe.**

**What is the 4/5 character code for this language, e.g EN-US etc.**

**Are their similiar "parent" languages, e.g EN already exists and you are wanting EN-GB?**

**Comment by bachi1968** [comment]
Which language do you want added? Please describe.
de - De

**Comment by Fma965** [comment]
No information provided /closed

**Comment by Fma965** [comment]
Syn3updater locale already exists.
