### ISSUE TITLE
Redundant Errors for Failed Multithreaded Downloads

### ISSUE THREAD

**Issue by egnarts12** [CyanLabs/Syn3Updater#198]
When 'Download Connections' is set to any value other than 1 and a download fails due to loss of Internet connectivity, an error message appears for each download thread. If download connections is set to 8 then 8 error boxes will appear on the screen. Each error must be acknowledged before continuing.

**To Reproduce**
1. Open 'Car Configuration'
2. Select any value above 1 in 'Download Connections'
3. Use Syn3 Updater to perform any action that involves downloaded files
4. Disconnect from the Internet or put the computer to sleep (then resume) while Syn3 Updater is downloading

**Expected behavior**
Only one error message box should appear or the download should be retried/resumed at least once.

**Desktop (please complete the following information):**
 - Windows Version: 11
 - Syn3 Updater Version: 2.11.10.0
 - Syn3 Updater Branch: Stable

**Comment by Fma965** [comment]
Inactive, closing
