### ISSUE TITLE
Wrong Time in Sync3 after update from 3.0 to 3.4

### ISSUE THREAD

**Issue by FKBOX** [CyanLabs/Syn3Updater#199]
Created the stick with the CyanLabs Syn3 updater.
After booting I got an error in a package.
That may be was on a cheap USB stick 4GB. So I took an new one 32GB what was on gpt, cleaned it with diskpart and did an new partition an created a stick again with the software.
Good luck, made it to the end.
But now I have the problem, that the clock sais no gps, try later. The time is UTC. Where I live is MET(UTC+2). If I change manual, it get back to UTC after seconds. There is no area, where I can change time zone.

**To Reproduce**
1. Go to 'clock'
2. Click on 'change time via arrows'
3. goes back to UTC after seconds
4. See error: wrong time
5. Carplay has no problems to navigate, so gps must be there.

**Expected behavior**
Change Time zone to UTC +2 /+1 for Wintertime

**Screenshots**
not needed, discription is clear.

**Desktop (please complete the following information): 
CYANLABS - SYN3 UPDATER - V2.12.2.0
Branch: Stable
Operating System: Microsoft Windows 11 Home (2009)

PREVIOUS CONFIGURATION
Version: 3.0.20204
Region: EU
Navigation: False
Install Mode: Automatische Erkennung (reformat)
Install Mode Overridden: False
My20 Protection Enabled: Automatische Erkennung

DESTINATION DETAILS
Mode: Drive
Model: VendorCo ProductCode USB Device
Size: 29,3GB
FileSystem: FAT32
Partition Type: MBR
AUTOINSTALL.LST
; CyanLabs Syn3Updater 2.12.2.0 Stable - reformat  Mode - Sync 3.4.23188 EU

[SYNCGen3.0_ALL_PRODUCT]
Item1 = RWDataCleaner TOOL - PU5T-14G386-BB_1690840002000.TAR.GZ
Open1 = SyncMyRide\PU5T-14G386-BB_1690840002000.TAR.GZ
Item2 = REFORMAT TOOL  - 1u5t-14g386-cb.tar.gz
Open2 = SyncMyRide\1u5t-14g386-cb.tar.gz
Options = AutoInstall

**Additional context**
I did a jailbreak on sync3 3.0 before by fmods. Is the fmods installer deleted bei reformating for update to 3.4.
And are the fmods apps compatible to this Cyanlabs updated version of sync3 3.4

**Comment by Fma965** [comment]
Not a Syn3Updater issue closed, post on our forum.
