### ISSUE TITLE
Crash in vehicle help?

### ISSUE THREAD

**Issue by russellpompa** [CyanLabs/Syn3Updater#202]
I've started with a president blank screen, 2019 F150. It was fully fictional, I performed a Sync i Matter Reset. I'm the end, after the Ford logo appears, the system appears to fail during boot and locks on the black screen. Pressing and holding power and forward buttons, does appear to force reboot, but the same boot sequence continues. I have already loaded and written As Builts with Forscan hoping I could get a full boot cycle on my own and without help from outside.

My computer showed that the SD card was created correctly.

I have inserted the flash drive into the USB with key on and engine on, 

Can you please help or guide me?

Thanks,

**Comment by Fma965** [comment]
We do not do support via github, post on our forum https://community.cyanlabs.net

Seems like you have MY20 and bricked.
