### ISSUE TITLE
"Failed to validate 4U5T-14G424-CF_1682464057000.TAR.GZ 3 times, aborting process" error

### ISSUE THREAD

**Issue by mkehrein** [CyanLabs/Syn3Updater#203]
**Describe the bug**
Received the screenshoted error message 3 times while trying to install.

**To Reproduce**

**Expected behavior**

**Screenshots**
Attached.
![error message](https://github.com/CyanLabs/Syn3Updater/assets/10878681/359ebd64-6772-4223-b32f-0d623c7830dd)

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 10, 8, 7] Unsure - was at public library
 - Syn3 Updater Version [e.g. 2.0.0.0] 2.12.5.0
 - Syn3 Updater Branch [e.g. Stable, Beta or Alpha] Stable

**Additional context**

**Comment by Fma965** [comment]
Not a bug
