### ISSUE TITLE
My unit is stuck in update mode it keeps telling me to put in a usb to update it's stuck on the screen with the update bar and mustang how can I fix this I can't master reset because it's not booting up

### ISSUE THREAD

**Issue by 4ndun** [CyanLabs/Syn3Updater#211]
**Describe the bug**
Please explain in as much detail as possible what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 10, 8, 7]
 - Syn3 Updater Version [e.g. 2.0.0.0]
 - Syn3 Updater Branch [e.g. Stable, Beta or Alpha]

**Additional context**

**Comment by Fma965** [comment]
not a syn3updater issue, post on our forum
