### ISSUE TITLE
Validate: 1U5T-14G421-BGL_1723602075000.TAR.GZ (Failed!, Downloading)

### ISSUE THREAD

**Issue by homeassistantby17** [CyanLabs/Syn3Updater#213]
**Describe the bug**
Persistent Validating error always for only the same file,1U5T-14G421-BGL_1723602075000.TAR.GZ

**To Reproduce**
Update Europe map only to version 2024
![image](https://github.com/user-attachments/assets/ef5908cb-59c1-42ac-9010-6b94171ba290)

**Expected behavior**
As per all the other files, successful download and verification. May be the archive is corrupted?

**Screenshots**
![image](https://github.com/user-attachments/assets/34e8f701-0c0a-477c-ba1e-c0d127eb1d42)

**Desktop (please complete the following information):**
 - Windows Version: 11 Pro
 - Syn3 Updater Version 2.13.0.0
 - Syn3 Updater Branch Stable

**Comment by Fma965** [comment]
not a issue with syn3updater
