### ISSUE TITLE
Nothing to download

### ISSUE THREAD

**Issue by fcaronte** [CyanLabs/Syn3Updater#26]
on last CI version 2.5.7.149 I can't download nothing. I choose "Europe" and other text field stay empty.
if i downgrade to stable update come back correctly
![image](https://user-images.githubusercontent.com/26366403/114215270-b1e12100-9965-11eb-8b53-bbdbaaceafe4.png)

**Comment by Fma965** [comment]
I can't replicate this issue

**Comment by fcaronte** [comment]
I don't know. i delete the folder, download again stable and is okay, then go to CI version and again same problem.
EDIT: problem gone with England language, so is something related to language UI

**Comment by Fma965** [comment]
Ahh that makes sense, noted :) Thanks.
