### ISSUE TITLE
Latest version freezes at formatting USB

### ISSUE THREAD

**Issue by liam-maps** [CyanLabs/Syn3Updater#4]
It says 12/01/2021 11:49:13 Re-creating partition table as MBR and formatting as ExFat on selected USB drive
and then nothing happens even after 3 hours.
The pendrive works perfectly, and tried other pendrives with no luck.

**Comment by Fma965** [comment]
> It says 12/01/2021 11:49:13 Re-creating partition table as MBR and formatting as ExFat on selected USB drive
> and then nothing happens even after 3 hours.
> The pendrive works perfectly, and tried other pendrives with no luck.

Sometimes this happens, have you tried multiple times? the format process is quite "hacky" as there isn't a good way ".NET Framework" method to ensure a USB drive is formatted as MBR

Can you confirm the latest version is 2.1.1.0 also

**Comment by Fma965** [comment]
Just to clarify the program won't require re-downloading files etc

**Comment by liam-maps** [comment]
> 
> 
> > It says 12/01/2021 11:49:13 Re-creating partition table as MBR and formatting as ExFat on selected USB drive
> > and then nothing happens even after 3 hours.
> > The pendrive works perfectly, and tried other pendrives with no luck.
> 
> Sometimes this happens, have you tried multiple times? the format process is quite "hacky" as there isn't a good way ".NET Framework" method to ensure a USB drive is formatted as MBR
> 
> Can you confirm the latest version is 2.1.1.0 also

Yes, the version is 2.1.1.0 and been trying since this morning
Ain't there a way to manually copy the files on my own and still have generated the autoinstall.lst?

**Comment by Fma965** [comment]
There isn't currently a way to manually do this, the whole point of this application was to prevent user error due to incorrectly formatted drives, if i added this functionality it would completely eliminate the whole reason for this application.

If the USB drive is already MBR and formatted as exFAT and named "CYANLABS" it will detect that the USB drive has previously been used by Syn3 Updater and allow you to skip formatting

**Comment by liam-maps** [comment]
> 
> 
> There isn't currently a way to manually do this, the whole point of this application was to prevent user error due to incorrectly formatted drives, if i added this functionality it would completely eliminate the whole reason for this application.
> 
> If the USB drive is already MBR and formatted as exFAT and named "CYANLABS" it will detect that the USB drive has previously been used by Syn3 Updater and allow you to skip formatting

I've managed to create the pendrive using the 1.0.1.1, the allowing it to download the 2.0.0.0 version and then blocking my internet to avoid the update.
Which, I'm seeing now is kinda stupid, because there are plenty of releases history here in the github.
Could I run into some potential issues if I've created the pendrive for the latest update (Autoinstall Mode - Sync 3.4.20282 EU), wihtout maps, using the 2.0.0.0 version of the app?
Thank you for your time and support.

**Comment by Fma965** [comment]
Weird as there isn't any changes to the USB creation that i can think of between these versions. it should be fine, updates were mostly to fix bugs with the application rather than with the install file generation

**Comment by Fma965** [comment]
This should now be fixed in 2.2.2
