### ISSUE TITLE
Download idles when Access Controlled Folder protection in Windows Security gets a pop-up

### ISSUE THREAD

**Issue by Dragunov404** [CyanLabs/Syn3Updater#66]
While downloading the files.

It happened to me I get a pop-up of those Controlled Access Folder protection to say it's blocked, I pressed to allow it, but the download of those file got stuck on 100% veryfing, so u need to cancel those one, restart, but now u better choose no to empty the folder.

So it only verifies the exiting files already and now I continues to download the others.

My suggestion is after allowing it, it just continues on its own

**Comment by Fma965** [comment]
Useful references

https://stackoverflow.com/questions/56703623/how-to-check-for-directory-write-permission-in-net-when-controlled-folder-acce

**Comment by Fma965** [comment]
Not something i can fix as the warning comes from Windows not the application. I will add a notice that shows if Controlled Folder Access is detected and Syn3 updater is not whitelisted but there is nothing more I can do.
afc3c762ce0ce33217cc965f6b59a77c55d8064a
