### ISSUE TITLE
MY20 toggle Issue

### ISSUE THREAD

**Issue by Dragunov404** [CyanLabs/Syn3Updater#67]
I think there is an issue with those MY20 Protection, cause if I don't activate Advanced Settings and so let MY20 protection on OFF, then program asks me when u click Start to begin downloading files for those MY20 protection, when clicking yes, the app crashes.

When u set Advanced Settings to ON, so u can set MY20 Protection to ON, the question is not asked and u can just start downloading the files

**Comment by Fma965** [comment]
![image](https://user-images.githubusercontent.com/1707290/120506817-2cef1280-c3be-11eb-8593-31de5fc579fb.png)

**Comment by Fma965** [comment]
Can't replicate this.
