### ISSUE TITLE
Negatives are allowed in Download Connections

### ISSUE THREAD

**Issue by SanD-82** [CyanLabs/Syn3Updater#84]
**Describe the bug**
At the configuration tab, you can get negative integers in the "download connections" field.

**To Reproduce**
1. Go to config
2. Click on current number of connections
3. Scroll down pass 0

**Expected behavior**
A minimum of 1 should be set for the field.

**Screenshots**
![image](https://user-images.githubusercontent.com/85264826/121239570-c8293180-c86f-11eb-9464-fedce32b6bae.png)

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version 2.7.4.10
 - Syn3 Updater Branch Alpha

**Comment by Fma965** [comment]
Adding a Minimum to the XAML results in the connections resetting to 1 on load of app each time, needs further diagnosis
