### ISSUE TITLE
If Advanced Options are disabled, Install Mode is FORCED depending on the last operation

### ISSUE THREAD

**Issue by SanD-82** [CyanLabs/Syn3Updater#86]
**Describe the bug**
Install Mode is forced to whatever option was AUTODETECTed and you can't change it, making Syn3Updater forced to do that.

**To Reproduce**
1. Go to Settings
2. Activate "Edit Advanced Options", set AUTODETECT in Install Mode. Disable "Edit Advanced Options"

![image](https://user-images.githubusercontent.com/85264826/121258137-ebaaa700-c884-11eb-9448-3a7b363bbc12.png)

![image](https://user-images.githubusercontent.com/85264826/121258162-f36a4b80-c884-11eb-8499-ac8ff2cf771b.png)

3. Go back to HOME tab, select a directory and select a packate:

![image](https://user-images.githubusercontent.com/85264826/121258311-20b6f980-c885-11eb-8b18-3679b567f8a2.png)

The install mode is REFORMAT, but not FORCED.

4. If you close the app now (or complete the process), the install method is forced:

![image](https://user-images.githubusercontent.com/85264826/121258460-4cd27a80-c885-11eb-866c-d2eb76357f87.png)

![image](https://user-images.githubusercontent.com/85264826/121258485-54921f00-c885-11eb-81d6-f4a4ef9f67e6.png)

**Expected behavior**
If Advanced Options are disabled, Install Mode should always be autodetect, not forced

**Screenshots**
Sent before.

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Syn3 Updater Version 2.7.4.10
 - Syn3 Updater Branch Alpha

**Comment by Fma965** [comment]
False close by automation processes
