### ISSUE TITLE
GUI guard regarding New Version Region

### ISSUE THREAD

**Issue by miatidis-storfund** [CyanLabs/Syn3Updater#88]
Since the "New Version" should be strictly based on the "Car Configuration" section otherwise APIM could fail, maybe in the New Version section:

![image](https://user-images.githubusercontent.com/47821856/121510580-75c34e80-c9f0-11eb-8a47-c0ff8959f040.png)

Region should just reveal the Configuration value using label instead of drop-down?

**Comment by Fma965** [comment]
No, this is by design, region can be changed but if you select a different region you are warned that this may not work without changes to asbuilt.

**Comment by Fma965** [comment]
![image](https://user-images.githubusercontent.com/1707290/121511567-ad29ff00-c9e0-11eb-9d55-f6c753647d91.png)
